version: '3'

services:
  node:
    build:
      target: final
    container_name: llprechner-backend-production
    entrypoint: dockerize node ./dist/server.js
    deploy:
        restart_policy:
            condition: on-failure
            max_attempts: 10
  angular:
    build:
      target: final
    deploy:
        restart_policy:
            condition: on-failure
            max_attempts: 10
    container_name: llprechner-frontend-production
    ports:
        - ${ANGULAR_PORT}:80
    restart: unless-stopped
    depends_on:
        - node

